export const CALLIOPE_DEPTH_01_JOB = {
  idempotency_key: "calliope-autonomous-depth-01",
  job_type: "MUSE_KNOWLEDGE_EXPANSION",
  muse_key: "calliope",
  title: "Calliope Autonomous Depth Experiment 01",
  mission:
    "Identify 10 high-quality, non-duplicative sources capable of adding useful depth to Calliope. Curate them, build a candidate Calliope knowledge expansion, ingest it into an isolated candidate environment, run the complete existing Calliope validation suite, compare it to the frozen baseline, diagnose regressions, attempt permitted repairs, revalidate, and prepare a release candidate. Do not modify the frozen baseline or production environment. Stop for human approval before release.",
  baseline_version: "muse-iq-v1.2",
  candidate_version: "calliope-depth-agent-01",
  status: "NEW",
  current_agent: null,
  priority: 60,
  risk_level: "LOW",
  requested_source_count: 10,
  max_retries: 3,
  requires_human_review: false,
  autonomy_policy: {
    research: true,
    curation: true,
    candidate_ingestion: true,
    validation: true,
    candidate_code_repair: true,
    production_release: false,
    canon_change: false,
    benchmark_change: false,
    production_deletion: false,
  },
  input: {
    muse_identity: "Calliope — Storyborne",
    target_capabilities: [
      "narrative perspective",
      "character",
      "scene",
      "dramatic tension",
      "story-song structure",
    ],
    research_behavior: {
      scout_more_than_needed: true,
      target_candidate_pool: 16,
      prefer_primary_or_authoritative_sources: true,
      preserve_provenance: true,
      avoid_unnecessary_duplication: true,
    },
    validation_behavior: {
      run_existing_frozen_suite_unchanged: true,
      compare_against_frozen_baseline: true,
      run_new_knowledge_exploratory_probes: true,
      zero_silent_regression: true,
    },
    release_behavior: {
      prepare_candidate_on_pass: true,
      require_human_approval: true,
    },
  },
} as const;
